# render.yaml - Configuration MySQL accessible pour N8N
services:
  - type: web
    name: coeur-mysql-db
    env: docker
    region: oregon
    plan: starter
    repo: https://github.com/JockaliaS/coeur-database.git  # MODIFIEZ avec votre repo
    branch: main
    dockerfilePath: ./Dockerfile

    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: coeur_db
      - key: MYSQL_USER
        value: coeur_user
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_CHARACTER_SET_SERVER
        value: utf8mb4
      - key: MYSQL_COLLATION_SERVER
        value: utf8mb4_unicode_ci
      - key: PORT
        value: "10000"

    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
